/**
 * Insert Shape — validate input before a database write
 *
 * Shows how SigilJS validates caller-supplied fields before
 * inserting a new record. Generated fields (ID, timestamps)
 * are added by the application layer after validation.
 *
 * No database connection. Plain objects only.
 */
import { oneOf, sigil } from '../../src/index.js';

// Insert contract — only caller-supplied fields, no generated fields
const NewUser = sigil.exact({
  email: String,
  name: String,
  role: oneOf('admin', 'user'),
});

// Caller input (e.g. from an API request body)
const input = {
  email: 'alex@example.com',
  name: 'Alex',
  role: 'user',
};

// Validate before insert
const validated = NewUser.parse(input);

// Application layer adds generated fields — SigilJS does not own these
const FIXED_NOW = '2026-01-01T00:00:00.000Z'; // fixed for determinism
const rowToInsert = {
  id: 'user_abc123', // generated by app or database
  ...validated,
  createdAt: FIXED_NOW,
  updatedAt: FIXED_NOW,
};

console.log('Validated insert:', validated);
console.log('Row to insert:', rowToInsert);
console.log('SigilJS validated:', Object.keys(validated).join(', '));
console.log('App added:', 'id, createdAt, updatedAt');
